doc/001_Samples/lesson1/lesson1/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

pr1101/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import user


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("rent/", include("rent_things.urls", namespace="rent_app")),
    path("users/", include("user.urls", namespace="users")),
    path("social-auth/", include("social_django.urls", namespace="social")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rent_things/urls.py
from django.urls import path
from rent_things.views import (
    test_session_view,
    index,
    ThingListView,
    CategoryListView,
    CategoryDetailView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    ThingDetailView,
    TagDetailView,
    TagListView,
    TagCreateView,
    TagDeleteView,
    TagUpdateView,
)


app_name = "rent_app"

urlpatterns = [
    path("test-session/", test_session_view, name="test_session"),
    path("", index, name="index"),
    path("things/", ThingListView.as_view(), name="things_list"),
    path("things/<int:pk>/", ThingDetailView.as_view(), name="thing_detail"),
    path("categories/", CategoryListView.as_view(), name="category_list"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category_detail"),
    path("categories/create/", CategoryCreateView.as_view(), name="category_create"),
    path(
        "categories/<int:pk>/delete/",
        CategoryDeleteView.as_view(),
        name="category_delete",
    ),
    path(
        "categories/<int:pk>/update/",
        CategoryUpdateView.as_view(),
        name="category_update",
    ),
    path("tags/", TagListView.as_view(), name="tag_list"),
    path("tags/<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("tags/create/", TagCreateView.as_view(), name="tag_create"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag_update"),
]

user/urls.py
from django.urls import path
from user.views import register


app_name = "users"

urlpatterns = [
    path("register/", register, name="register"),
]

rent_things/models.py
from pathlib import Path
from uuid import uuid4

from django.contrib.auth import get_user_model
from django.db import models
from django.utils.text import slugify

User = get_user_model()


def get_image_path(instance, filename: str, subfolder: Path = Path("uploads")) -> Path:
    filename = (
        f"{slugify(filename.partition('.')[0])}_{uuid4()}" + Path(filename).suffix
    )
    return Path(subfolder) / filename


class Image(models.Model):
    image = models.ImageField(upload_to=get_image_path)
    description = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.image.name


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    parent = models.ForeignKey(
        "self",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="children",
    )

    class Meta:
        verbose_name_plural = "categories"
        ordering = ["name", "parent__name"]
        unique_together = ["name", "parent"]

    def __str__(self):
        return self.name


class Tag(models.Model):
    TAG_PREFIX = "##"
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        self.name = self.name.translate(str.maketrans(" ", "_", ".,;:!?#")).lower()
        self.name = self.TAG_PREFIX + self.name
        return super().save(force_insert, force_update, using, update_fields)


class Thing(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="things"
    )
    tags = models.ManyToManyField(Tag, related_name="things")
    is_active = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    compensation = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="things")
    images = models.ManyToManyField(Image, blank=True, related_name="things")

    class Meta:
        ordering = ["name", "created_at"]

    def __str__(self):
        return self.name


class Displacement(models.Model):
    class Condition(models.TextChoices):
        NEW = "N", "New - traces of use are imperceptible"
        EXCELLENT = "E", "Excellent - traces of use are minimal"
        GOOD = "G", "Good - visible signs of use"
        SATISFACTORY = "S", "Satisfactory - significant traces of use, but possible use"
        BAD = "B", "Bad - the item is damaged, but can be repaired"
        VERY_BAD = "VB", "Very bad - the item is damaged and cannot be repaired"

    thing = models.ForeignKey(
        Thing, on_delete=models.CASCADE, related_name="displacements"
    )
    to = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="displacements",
        help_text="User to whom the thing is displaced",
    )
    by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="supported_displacements",
        help_text="User who displaced the thing",
    )
    date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    description = models.TextField(null=True, blank=True)
    condition = models.CharField(
        max_length=2, choices=Condition, default=Condition.EXCELLENT
    )

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return f"{self.thing} -> {self.to} by {self.by}"

rent_things/forms.py
from django import forms

from .models import Tag, Category


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ["name", "description"]
        widgets = {
            "name": forms.TextInput(
                attrs={"placeholder": "обов'язково введіть назву тегу"}
            ),
            "description": forms.Textarea(
                attrs={"placeholder": "Опишіть як використовувати цей тег"}
            ),
        }


class ThingSearchForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        required=False,
        widget=forms.TextInput(attrs={"placeholder": "Пошук за назвою"}),
    )
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.filter(is_active=True),
        required=False,
        widget=forms.CheckboxSelectMultiple,
    )
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.filter(is_active=True),
        required=False,
        widget=forms.CheckboxSelectMultiple,
    )

rent_things/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.http import HttpResponse, HttpRequest, Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import generic

from . import db_services
from .forms import TagForm, ThingSearchForm
from .models import Thing, Category, Tag


def test_session_view(request: HttpRequest) -> HttpResponse:
    request.session["test"] = "test session value"
    return HttpResponse(
        "<h1>Session test</h1>"
        "<hr>"
        f"Session data: {request.session.items()}<br>"
        f"Session value: {request.session.get('test', 'No session value')}"
    )


def index(request: HttpRequest) -> HttpResponse:
    num_things = Thing.objects.count()
    num_categories = Category.objects.count()
    num_tags = Tag.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1
    context = {
        "num_things": num_things,
        "num_categories": num_categories,
        "num_tags": num_tags,
        "num_visits": num_visits,
    }
    return render(request, "rent_things/index.html", context=context)


class ThingListView(generic.ListView):
    model = Thing
    template_name = (
        "rent_things/things_list.html"  # Default: <app_label>/<model_name>_list.html
    )
    context_object_name = "things"  # Default: object_list
    queryset = Thing.objects.filter(is_active=True).select_related(
        "category"
    )  # Default: Model.objects.all()
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["search_form"] = ThingSearchForm(initial=self.request.GET)
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get("name")
        categories = self.request.GET.getlist("categories")
        tags = self.request.GET.getlist("tags")
        if name:
            queryset = queryset.filter(name__icontains=name)
        if tags:
            queryset = queryset.filter(tags__in=tags).distinct()
        if categories:
            all_categories = db_services.categories.get_all_child_categories(categories)
            queryset = queryset.filter(category__in=all_categories).distinct()
        return queryset


class ThingDetailView(generic.DetailView):
    model = Thing
    template_name = (
        "rent_things/thing_detail.html"  # Default: <app_label>/<model_name>_detail.html
    )
    context_object_name = "thing"  # Default: object
    queryset = Thing.objects.filter(is_active=True)  # Default: Model.objects.all()


class CategoryListView(generic.ListView):
    model = Category
    context_object_name = "categories"
    queryset = Category.objects.filter(is_active=True).annotate(
        Count("things")
    )  # Default: Model.objects.all()
    paginate_by = 5


class CategoryDetailView(generic.DetailView):
    model = Category
    context_object_name = "category"
    queryset = (
        Category.objects.filter(is_active=True)
        .select_related("parent")
        .prefetch_related("children")
    )


class CategoryCreateView(LoginRequiredMixin, generic.CreateView):
    model = Category
    fields = ["name", "description", "parent"]
    template_name = "rent_things/category_form.html"

    def get_success_url(self):
        return reverse_lazy("rent_app:category_detail", kwargs={"pk": self.object.pk})


class CategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Category
    fields = ["name", "description", "parent"]
    template_name = "rent_things/category_form.html"

    def get_success_url(self):
        return reverse_lazy("rent_app:category_detail", kwargs={"pk": self.object.pk})


class CategoryDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Category
    template_name = "rent_things/category_confirm_delete.html"
    success_url = reverse_lazy("rent_app:category_list")

    def get_queryset(self):
        return Category.objects.filter(is_active=True).annotate(
            things_count=Count("things")
        )


class TagListView(generic.ListView):
    model = Tag
    context_object_name = "tags"
    queryset = (
        Tag.objects.filter(is_active=True)
        .annotate(things_count=Count("things"))
        .values("id", "name", "things_count")
    )


class TagDetailView(generic.DetailView):
    model = Tag
    context_object_name = "tag"
    queryset = Tag.objects.filter(is_active=True)


class TagCreateView(LoginRequiredMixin, generic.CreateView):
    model = Tag
    form_class = TagForm
    template_name = "rent_things/tag_form.html"
    success_url = reverse_lazy("rent_app:tag_list")


class TagUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Tag
    form_class = TagForm
    template_name = "rent_things/tag_form.html"
    success_url = reverse_lazy("rent_app:tag_list")


class TagDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Tag
    template_name = "rent_things/tag_confirm_delete.html"
    success_url = reverse_lazy("rent_app:tag_list")

    def get_queryset(self):
        return Tag.objects.filter(is_active=True).annotate(things_count=Count("things"))

templates/rent_things/category_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Видалити категорію:</h1>
  <hr>
  <p><i>При видаленні категорії <strong>"{{ object.name }}"</strong> будуть видалені також речі які до неї відносяться
    (всього: {{ object.things_count }}). Підтвердіть видалення.</i></p>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    <input type="submit" value="Підтвердити видалення" class="btn btn-danger">
{% endblock %}

templates/rent_things/category_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      <h1>{{ category.name }}</h1>
      <hr>
      {% if category.description %}
        <p>{{ category.description }}</p>
      {% else %}
        <p>Опис не надано</p>
      {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h4>батьківська категорія:</h4>
      {% if category.parent %}
        <a href="{% url 'rent_app:category_detail' category.parent.id %}">{{ category.parent.name }}</a>
      {% else %}
        <p>батьківська категорія відсутня</p>
      {% endif %}
    </div>
    <div class="col-md-6">
      <h4>дочірні категорії:</h4>
      {% if category.children.all %}
        <ul>
          {% for child in category.children.all %}
            <li><a href="{% url 'rent_app:category_detail' child.id %}">{{ child.name }}</a></li>
          {% endfor %}
        </ul>
      {% else %}
        <p>дочірні категорії відсутні</p>
      {% endif %}
    </div>
  </div>

{% endblock %}

templates/rent_things/category_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Оновити,Створити нову" }} категорію:</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Створити">
  </form>
{% endblock %}

templates/rent_things/category_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Категорії:<a style="float: right" href="{% url 'rent_app:category_create' %}">➕</a></h1>
  <hr>
  {% if categories %}

    <table class="table">
      <tr>
        <th>Назва</th>
        <th>Кількість речей</th>
        <th>Оновити</th>
        <th>Видалити</th>
      </tr>

      {% for category in categories %}
        <tr>
          <td><a href="{% url 'rent_app:category_detail' category.id %}">{{ category.name }}</a></td>
          <td>{{ category.things__count }}</td>
          <td><a href="{% url 'rent_app:category_update' category.id %}">🔄</a></td>
          <td><a href="{% url 'rent_app:category_delete' category.id %}">❌</a></td>
        </tr>
      {% endfor %}

    </table>
  {% else %}
    <p>There are no categories in the database.</p>
  {% endif %}
{% endblock %}

templates/rent_things/index.html
{% extends 'base.html' %}

{% block title %}
  <title>Home page</title>
{% endblock %}

{% block content %}
  <h1>Welcome to a world where things live a full life!</h1>
  <hr>
  <ul>
    <li>There are {{ num_things }} things in the database.</li>
    <li>There are {{ num_categories }} categories in the database.</li>
    <li>There are {{ num_tags }} tags in the database.</li>
  </ul>
  <hr>
  <p class="fixed-bottom small color: grey">You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}</p>
{% endblock %}

templates/rent_things/tag_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Видалити тег:</h1>
  <hr>
  <p><i>Тег <strong>"{{ object.name }}"</strong> використовується для опису {{ object.things_count }} реч{{ object.things_count|pluralize:"і,ей" }}. Підтвердіть видалення.</i></p>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    <input type="submit" value="Підтвердити видалення" class="btn btn-danger">
{% endblock %}

templates/rent_things/tag_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ tag.name }}</h1>
  <hr>
  {% if tag.description %}
    <p>{{ tag.description }}</p>
  {% else %}
    <p>There is no description for this tag.</p>
  {% endif %}
{% endblock %}

templates/rent_things/tag_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Створіть новий тег:</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Створити">
  </form>
{% endblock %}

templates/rent_things/tag_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Теги:<a style="float: right" href="{% url 'rent_app:tag_create' %}">➕</a></h1>
  <hr>
  <ul>
    {% for tag in tags %}
      <li>
        <a href="{% url 'rent_app:tag_detail'  tag.id %}"><strong>{{ tag.name }}</strong> (використовується
          для {{ tag.things_count }} речей)</a>
      </li>
    {% empty %}
      <p>There are no tags.</p>
    {% endfor %}
  </ul>
{% endblock %}

templates/rent_things/thing_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <h1>{{ thing.name|capfirst }}</h1>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-sm-6">
      <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">

          {% for image in thing.images.all %}
            <div class="carousel-item {% if forloop.first %} active {% endif %}">
              <img src="{{ image.image.url }}" class="img-fluid" style="max-height: 450px;" alt="{{ image.description }}">
            </div>
          {% empty %}

            <div class="carousel-item active">
              <img src="{% static 'images/No_image_available.svg.png' %}" class="d-block w-100" alt="No image provided">
            </div>

          {% endfor %}


        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
                data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
                data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
    <div class="col-sm-6">
      <p><strong>Category: </strong>{{ thing.category.name|lower }}</p>
      <p><strong>Compensatory price: </strong>{{ thing.compensation }}</p>
      <p><strong>Use price: </strong>{{ thing.price }}</p>
      <p><strong>Owner: </strong><a href="#">{{ thing.owner.username }}</a></p>
    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-sm-12">
      <p>{{ thing.description }}</p>
    </div>
  </div>

{% endblock %}

templates/rent_things/things_list.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Речі:</h1>

  <hr>
  {% if things %}
    <ul>
      {% for thing in things %}
        <li>
          <a href="{% url 'rent_app:thing_detail'  thing.id %}">{{ thing.name }}</a> (<a style="color: aqua"
                                                                                         href="#">{{ thing.category }}</a>)
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no things in the database.</p>
  {% endif %}

{% endblock %}

{% block search %}
  <form action="" method="get">
  <div class="d-grid">
     <input type="submit" value="Знайти" class="btn btn-outline-primary">
  </div>
    <ul class="list-group">
      {% for field in search_form %}
        <li class="list-group-item">
          {{ field|as_crispy_field }}
        </li>
      {% endfor %}
      
    </ul>
  </form>
{% endblock %}