doc/001_Samples/django_courses/django_courses/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("lesson_1/", include("lesson_1.urls")),
    path("admin/", admin.site.urls),
]

doc/001_Samples/lesson1/lesson1/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

pr1101/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import user


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("rent/", include("rent_things.urls", namespace="rent_app")),
    path("users/", include("user.urls", namespace="users")),
    path("social-auth/", include("social_django.urls", namespace="social")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rent_things/urls.py
from django.urls import path
from rent_things.views import (
    test_session_view,
    index,
    ThingListView,
    CategoryListView,
    CategoryDetailView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    ThingDetailView,
    TagDetailView,
    TagListView,
    TagCreateView,
    TagDeleteView,
    TagUpdateView,
)


app_name = "rent_app"

urlpatterns = [
    path("test-session/", test_session_view, name="test_session"),
    path("", index, name="index"),
    path("things/", ThingListView.as_view(), name="things_list"),
    path("things/<int:pk>/", ThingDetailView.as_view(), name="thing_detail"),
    path("categories/", CategoryListView.as_view(), name="category_list"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category_detail"),
    path("categories/create/", CategoryCreateView.as_view(), name="category_create"),
    path(
        "categories/<int:pk>/delete/",
        CategoryDeleteView.as_view(),
        name="category_delete",
    ),
    path(
        "categories/<int:pk>/update/",
        CategoryUpdateView.as_view(),
        name="category_update",
    ),
    path("tags/", TagListView.as_view(), name="tag_list"),
    path("tags/<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("tags/create/", TagCreateView.as_view(), name="tag_create"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag_update"),
]

user/urls.py
from django.urls import path
from user.views import register


app_name = "users"

urlpatterns = [
    path("register/", register, name="register"),
]

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a>
      </li>
    {% endif %}
    <li class="page-item active"><span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span></li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
{% block sidebar %}
  <div class="d-grid gap-2">
    <h4>вітаю, {{ user.username|default:"гість" }}!</h4>
    {% if user.is_authenticated %}
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-secondary form-control">Вийти</button>
      </form>
      <a href="{% url 'password_change' %}" class="btn btn-outline-secondary">Змінити пароль</a>
    {% else %}
      <a href="{% url 'login' %}" class="btn btn-outline-secondary">Увійти</a>
      <a href="{% url 'password_reset' %}" class="btn btn-outline-secondary">Відновити пароль</a>
      <a href="{% url 'users:register' %}" class="btn btn-outline-secondary">Зареєструватися</a>
    {% endif %}
  </div>

  <div>
    <ul class="list-group">
      <li class="list-group-item"><a href="{% url 'rent_app:index' %}">Home</a></li>
      <li class="list-group-item"><a href="{% url 'rent_app:things_list' %}">Things</a></li>
      <li class="list-group-item"><a href="{% url 'rent_app:category_list' %}">Categories</a></li>
      <li class="list-group-item"><a href="{% url 'rent_app:tag_list' %}">Tags</a></li>
    </ul>
  </div>
{% endblock %}